[package]
name = "test1_hello"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[features]
witness = []
wasmbind = ["witness"]

[dependencies]
primitive-types = {version="0.12.1", default-features = false}
wasm-bindgen = "0.2.83"